# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TXOCR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  
  # Pods for TXOCR

  target 'TXOCRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TXOCRUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
